sudo: required
services:
  - docker

before_install:
  - docker build -t cdifranco1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cdifranco1/react-test npm test

after_success:
  - docker build -t cdifranco1/multi-client ./client
  - docker build -t cdifranco1/multi-nginx ./nginx
  - docker build -t cdifranco1/multi-server ./server
  - docker build -t cdifranco1/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cdifranco1/multi-client
  - docker push cdifranco1/multi-nginx
  - docker push cdifranco1/multi-server
  - docker push cdifranco1/multi-worker